# Generated by Django 4.1.7 on 2023-02-16 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
    ]
