# Generated by Django 4.1.7 on 2023-02-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app1', '0003_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
