# Generated by Django 4.1.7 on 2023-02-18 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eshopadmin_app1', '0002_alter_shopdetails_address_alter_shopdetails_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCategorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('date_of', models.DateTimeField(auto_now_add=True)),
                ('is_available', models.BooleanField(default=True)),
                ('image1', models.ImageField(max_length=200, upload_to='images/')),
                ('image2', models.ImageField(max_length=200, upload_to='images/')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshopadmin_product.shopcategorys')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshopadmin_app1.shopdetails')),
            ],
        ),
    ]
