# Generated by Django 4.1.7 on 2023-03-11 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'CustomUser'},
        ),
        migrations.AlterModelOptions(
            name='shopdetails',
            options={'verbose_name': 'ShopDetails'},
        ),
        migrations.AlterModelOptions(
            name='shopstaff',
            options={'verbose_name': 'ShopStaff'},
        ),
        migrations.AddField(
            model_name='shopproducts',
            name='discription',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
