# Generated by Django 4.1.7 on 2023-03-14 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_productvariation_shopproducts_variation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndUserOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_credit', models.IntegerField(null=True)),
                ('payment_debit', models.IntegerField(null=True)),
                ('payment_id', models.CharField(max_length=25, null=True)),
                ('order_id', models.CharField(max_length=25, null=True)),
                ('total_amount', models.IntegerField()),
                ('order_status', models.CharField(choices=[('pending', 'Pending'), ('cancel', 'Cancel'), ('complete', 'Complete'), ('refund', 'Refund')], max_length=20)),
                ('payment_type', models.CharField(choices=[('cashonhand', 'Cash On hand'), ('online', 'Online')], max_length=20)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordershop', to='superadmin.shopdetails')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderstaff', to='superadmin.shopstaff')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orederuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
