# Generated by Django 4.1.7 on 2023-04-01 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_alter_useraddress_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopstaff',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopstaff', to='superadmin.shopdetails'),
        ),
    ]
