# Generated by Django 4.1.7 on 2023-04-05 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_alter_shopstaff_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduserorders',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='useradderss', to='superadmin.useraddress'),
            preserve_default=False,
        ),
    ]
