# Generated by Django 4.1.7 on 2023-04-07 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_enduserorders_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enduserorders',
            name='payment_type',
            field=models.CharField(choices=[('cashondelivery', 'Cash On Delivery'), ('online', 'Online')], max_length=20),
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('rate', models.IntegerField()),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewproduct', to='superadmin.shopproducts')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewshop', to='superadmin.shopdetails')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewuser', to='superadmin.usersdetails')),
            ],
        ),
    ]
