# Generated by Django 4.1.7 on 2023-02-27 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eshopadmin_app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndUserOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cancle', 'Cancle'), ('complete', 'Complete')], max_length=20)),
                ('payment_type', models.CharField(choices=[('cashonpurchase', 'Cash On Purchase'), ('onlinepurchase', 'Online Purchase')], max_length=20)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='eshopadmin_app1.shopdetails')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='eshopadmin_app1.shopstaff')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('product_price', models.IntegerField()),
                ('product_image1', models.ImageField(max_length=200, upload_to='order/')),
                ('product_image2', models.ImageField(max_length=200, upload_to='order/')),
                ('quantity', models.IntegerField()),
                ('total', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='enduser_orders.enduserorders')),
            ],
        ),
    ]
