# Generated by Django 4.1.7 on 2023-03-03 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshopadmin_app1', '0001_initial'),
        ('enduser_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enduserorders',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='eshopadmin_app1.shopstaff'),
        ),
    ]
