# Generated by Django 4.1.7 on 2023-03-03 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshopadmin_product', '0002_productimages'),
        ('enduser_orders', '0002_alter_enduserorders_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproducts',
            name='product_image1',
        ),
        migrations.RemoveField(
            model_name='orderproducts',
            name='product_image2',
        ),
        migrations.AddField(
            model_name='enduserorders',
            name='payment_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderproducts',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eshopadmin_product.productimages'),
            preserve_default=False,
        ),
    ]
