# Generated by Django 4.1.7 on 2023-03-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enduser_orders', '0003_remove_orderproducts_product_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduserorders',
            name='order_id',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='enduserorders',
            name='payment_id',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
